// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCej1CUucVyzHXEcMmkeUues50UOBk6LmA',
    appId: '1:319019961476:web:c7ec4898ffe04eb9eb86d1',
    messagingSenderId: '319019961476',
    projectId: 'word-cards-mainor-2025-spring',
    authDomain: 'word-cards-mainor-2025-spring.firebaseapp.com',
    storageBucket: 'word-cards-mainor-2025-spring.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_2ZBffoJfOW_qpZ4G1vov_L3b0UTpSs8',
    appId: '1:319019961476:android:fe826256e3a99117eb86d1',
    messagingSenderId: '319019961476',
    projectId: 'word-cards-mainor-2025-spring',
    storageBucket: 'word-cards-mainor-2025-spring.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9fcdqype-pc_P-IvnEFLxwZNPNGOoQvA',
    appId: '1:319019961476:ios:0e141854fd767914eb86d1',
    messagingSenderId: '319019961476',
    projectId: 'word-cards-mainor-2025-spring',
    storageBucket: 'word-cards-mainor-2025-spring.firebasestorage.app',
    iosBundleId: 'com.mainor.wordcards.wordCardsMainor2025Spring',
  );
}
